### ISSUE TITLE
Message timeout error from nsqd causes socket connection to nsqd to be closed, even when it is not a connection error

### ISSUE THREAD

**Issue by jferretti-life** [sproutsocial/nsq-j#25]
Hello. While testing, I noticed some exceptions in my consumer service related to the E_FIN_FAILED error from nsqd.

The nsqd `--msg-timeout` argument is set to 1 minute, and it is timing out of my messages due to a slow consumer. nsq-j, on the consumer side of things, gets the following error when invoking finish on one of these timed out messages.

```
 2020-01-05 03:59:09.851 [ERROR] [nsq-read-0] c.s.n.Connection : read thread exception. con:SubCon:nsqd-internal circleObserved.geoshort-write#ephemeral
 com.sproutsocial.nsq.NSQException: error from nsqd:E_FIN_FAILED FIN 0c9644943b7e6029 failed ID not in flight
     at com.sproutsocial.nsq.Connection.readResponse(Connection.java:239) ~[nsq-j-0.9.4.jar!/:?]
     at com.sproutsocial.nsq.Connection.read(Connection.java:255) [nsq-j-0.9.4.jar!/:?]
     at com.sproutsocial.nsq.Connection.access$400(Connection.java:25) [nsq-j-0.9.4.jar!/:?]
     at com.sproutsocial.nsq.Connection$2.run(Connection.java:94) [nsq-j-0.9.4.jar!/:?]
```

The problem is that nsq-j is checking if the message equals `E_FIN_FAILED`, but instead, the message equals `E_FIN_FAILED FIN 0c9644943b7e6029 failed ID not in flight`. This causes the following NSQException to be thrown.

From com.sproutsocial.nsq.Connection:
```
private static final Set<String> nonFatalErrors = Collections.unmodifiableSet(new HashSet<String>(
        Arrays.asList("E_FIN_FAILED", "E_REQ_FAILED", "E_TOUCH_FAILED")));
...

String error = readAscii(size - 4);
if (nonFatalErrors.contains(error)) {
    logger.warn("non fatal nsqd error:{} probably due to message timeout", error);
}
else {
    throw new NSQException("error from nsqd:" + error);
}
```

Since a NSQException is thrown, the connection to nsqd is closed. All of the inflight messages are associated with this connection, and now they get the following error when they complete their message.

```
2020-01-05 03:59:36.811 [ERROR]    53 --- [       nsq-co-0] c.s.n.SubConnection                      : finish error. SubCon:nsqd-internal circleObserved.geoshort-write#ephemeral lastFlush:27.0 lastHeartbeat:54.9 unflushedCount:8        inFlight:16 maxInFlight:25 fin:24 req:0
 java.net.SocketException: Socket closed
     at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113) ~[?:?]
     at java.net.SocketOutputStream.write(SocketOutputStream.java:150) ~[?:?]
     at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) ~[?:?]
     at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142) ~[?:?]
     at java.io.DataOutputStream.flush(DataOutputStream.java:123) ~[?:?]
     at com.sproutsocial.nsq.Connection.flush(Connection.java:220) ~[nsq-j-0.9.4.jar!/:?]
     at com.sproutsocial.nsq.SubConnection.checkFlush(SubConnection.java:104) ~[nsq-j-0.9.4.jar!/:?]
     at com.sproutsocial.nsq.SubConnection.messageDone(SubConnection.java:74) ~[nsq-j-0.9.4.jar!/:?]
     at com.sproutsocial.nsq.SubConnection.finish(SubConnection.java:47) ~[nsq-j-0.9.4.jar!/:?]
     at com.sproutsocial.nsq.NSQMessage.finish(NSQMessage.java:48) ~[nsq-j-0.9.4.jar!/:?]
     at com.services.ui.nsq.CircleObservedConsumer$MessageResult$1.onComplete(CircleObservedConsumer.java:64) ~[classes!/:0.0.1-SNAPSHOT]
     at com.services.ui.nsq.CircleObservedConsumer.handleMessage(CircleObservedConsumer.java:200) ~[classes!/:0.0.1-SNAPSHOT]
     at com.sproutsocial.nsq.SubConnection$3.run(SubConnection.java:178) [nsq-j-0.9.4.jar!/:?]
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
     at java.lang.Thread.run(Thread.java:834) [?:?]
```

What I expect to happen:
I expect the `E_FIN_FAILED FIN 0c9644943b7e6029 failed ID not in flight` error to be considered non-fatal, and only logged at the warning level.

What actually happens:
The `E_FIN_FAILED FIN 0c9644943b7e6029 failed ID not in flight` causes a fatal exception, causing the socket connection to nsqd to be closed.

Repeatable, 100%. To reproduce:

1. run nsqd (nsqio/nsq:v1.2.0) with the default timeout (1m)
2. create a consumer that sleeps for 5s, and then invokes message.finish()
3. run that consumer with one thread, 25 in-flight
4. post 100 messages to nsqd for that topic
5. wait for  NSQException to occur after a minute
6. as each in-flight is consumed, wait for SocketException to be thrown during the message.finish() call

**Comment by robseed** [comment]
Thanks for the detailed bug report. 
This must be a change in a newer version of nsq.
I'll have a fix shortly.

**Comment by jferretti-life** [comment]
I had some free time and wanted to offer a solution for this issue. 

https://github.com/sproutsocial/nsq-j/pull/27

It fixed my use-case. Any suggestions?

**Comment by jferretti-life** [comment]
I updated the PR to move the inner helper class to its own file, so that I can use it for issue 26.

This is my first public PR. Let me know if you would like anything changed. My first goal is to create a repeatable test case showing the error, and then verify it works after the fix.

**Comment by AncestorDragon** [comment]
Have you solved the Finish error ？

**Comment by jferretti-life** [comment]
Yes, at least for my use-case. It is in a forked branch awaiting PR approval. https://github.com/sproutsocial/nsq-j/pull/27

**Comment by robseed** [comment]
Should be fixed
